### ISSUE TITLE
invalid privacy api class

### ISSUE THREAD

**Issue by danmarsden** [Tutoom/moodle-mod_tutoom#1]
it looks like you have implemented the null provider privacy class, but your plugin passes user information to an external source (users fullname/email address etc.)

for more information see:
https://moodledev.io/docs/apis/subsystems/privacy/#indicating-that-you-export-data-to-an-external-location

note this is a blocker for plugins db approval.

**Comment by jimmy-sandoval** [comment]
Hi @danmarsden nice to meet you!

We uploaded yours suggestions on this PR: https://github.com/Tutoom/tutoom-moodle-plugin/pull/40

**Comment by danmarsden** [comment]
please note - I do not review PR's on your own repository - you need to do that process yourself and merge when tested etc  :-)
