### ISSUE TITLE
invalid location for config settings.

### ISSUE THREAD

**Issue by danmarsden** [Tutoom/moodle-mod_tutoom#10]
Moodle plugins should not store their settings in the global $CFG var, but use the config_plugins table - 

To get these you would use get_config($plugin, $name). To set them use set_config($name, $value, $plugin).

more information on admin settings is here: https://moodledev.io/docs/apis/subsystems/admin

Note this is usually a blocker for plugins db approval.

**Comment by raortegar** [comment]
Hi @jesusvaldivia 

I think this issue is the same as this one https://github.com/Tutoom/moodle-mod_tutoom/issues/5 
But the code needs to be merged. 

Thanks!
