### ISSUE TITLE
tutoom_ajax.php does not validate user can perform actions.

### ISSUE THREAD

**Issue by danmarsden** [Tutoom/moodle-mod_tutoom#11]
It looks like the tutoom_ajax.php file can be called by anonymous users who can then create rooms/ger_recordings/join meetings - which seems incorrect?

What's the purpose of the if (!$params['mobil']) { check allowing the require_login() to also be bypassed?

it should also be checking - can this logged in user access this course - otherwise anonymous users could join the tutoom session for courses they should not be able to access too?

**Comment by jesusvaldivia** [comment]
Hi Dan 

tutoom_ajax.php has internal checksum validation that is checked on the server. If any anonymous user makes a call, it will fail because it is not authenticated by the checksum parameter.

Do you have any other questions about it?

**Comment by jesusvaldivia** [comment]
Hi Dan

I see the problem, $params['mobil'] is a parameter that is not being used and causes logging to be skipped.

We have updated the code with the correct please review.

**Comment by danmarsden** [comment]
thanks - I don't tend to review again until you have merged all patches, and updated the plugins db with the new code and flagged it as ready for review. :-)
