### ISSUE TITLE
please use Moodle's core "curl" class instead of directly calling curl_init()

### ISSUE THREAD

**Issue by danmarsden** [Tutoom/moodle-mod_tutoom#4]
Please don't initate curl_init() directly but use Moodle's own "curl" class which is a wrapper on PHP's curl functions.

Many organisations put their moodle site behind a web proxy and the internal curl wrapper takes care of this for you.

**Comment by jimmy-sandoval** [comment]
Hi, we don´t find about Moodle's own "curl". Please, can you share a link?

We use about PHP's own "curl".

**Comment by danmarsden** [comment]
Moodle has a wrapper on the PHP curl class helpfully called "curl" - if you search Moodle's core code for "curl" you should see several places where it is used that you can use to learn from.

**Comment by jimmy-sandoval** [comment]
Hello @danmarsden and @raortegar

We updated yours suggestions on this PR: https://github.com/Tutoom/moodle-mod_tutoom/pull/8

Thanks for your supports.
